services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  backend:
    image: priyanshu72881370/dd-backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/test

  frontend:
    image: priyanshu72881370/dd-frontend:latest
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend