name: CI-CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend Image
        run: docker build -t priyanshu72881370/dd-backend:latest ./backend

      - name: Build Frontend Image
        run: docker build -t priyanshu72881370/dd-frontend:latest ./frontend

      - name: Push Docker Images
        run: |
          docker push priyanshu72881370/dd-backend:latest
          docker push priyanshu72881370/dd-frontend:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Go to home directory
            cd /home/ubuntu

            # Clone repo if not exists
            if [ ! -d "assignment" ]; then
              git clone https://github.com/priyanshu72881/assignment.git
            fi

            cd assignment

            # Pull latest code
            git pull origin main

            # Clean old docker junk (avoid no space issue)
            sudo docker system prune -a -f

            # Stop old containers
            sudo docker-compose down

            # Pull latest images from Docker Hub
            sudo docker-compose pull

            # Start containers
            sudo docker-compose up -d
